// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPrDkMEPM9--4IyN7XQPElLVc_ID3qOnw',
    appId: '1:540078476032:web:a7529b968c3718b45401e5',
    messagingSenderId: '540078476032',
    projectId: 'car-meta-ca20b',
    authDomain: 'car-meta-ca20b.firebaseapp.com',
    storageBucket: 'car-meta-ca20b.appspot.com',
    measurementId: 'G-T14ESNZGG2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAK7U80mdSLrGxF1alQN3OGN7ttaDVpvkk',
    appId: '1:540078476032:android:7a9908a311cb85175401e5',
    messagingSenderId: '540078476032',
    projectId: 'car-meta-ca20b',
    storageBucket: 'car-meta-ca20b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDk4waa-hSw7oInB9-WPeI6uOo2D2U1rmY',
    appId: '1:540078476032:ios:1a8d701ce20ef1a15401e5',
    messagingSenderId: '540078476032',
    projectId: 'car-meta-ca20b',
    storageBucket: 'car-meta-ca20b.appspot.com',
    iosBundleId: 'com.example.carMeta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDk4waa-hSw7oInB9-WPeI6uOo2D2U1rmY',
    appId: '1:540078476032:ios:f4925ee9e894c8715401e5',
    messagingSenderId: '540078476032',
    projectId: 'car-meta-ca20b',
    storageBucket: 'car-meta-ca20b.appspot.com',
    iosBundleId: 'com.example.carMeta.RunnerTests',
  );
}
